-- CreateTable
CREATE TABLE User (
    id INTEGER NOT NULL AUTO_INCREMENT,
    email VARCHAR(191) NOT NULL,
    password VARCHAR(191) NOT NULL,
    full_name VARCHAR(191) NOT NULL,

    UNIQUE INDEX User_email_key(email),
    PRIMARY KEY (id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE Notes (
    id INTEGER NOT NULL AUTO_INCREMENT,
    content VARCHAR(191) NOT NULL,
    user_id INTEGER NOT NULL,
    createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updatedAt DATETIME(3) NOT NULL,

    PRIMARY KEY (id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE Notes ADD CONSTRAINT Notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE RESTRICT ON UPDATE CASCADE;
